# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d8eeaba9fd7324b5b495f350c32f3a7cea912634a494df53f2f3b8cd91612732056cc517a56e6ed788fb6ed0504cdc2a4c3cd445cc46e22123ffed115519ae06

test:
  secret_key_base: ce9ff015b4d54d1f40baa5ae7a843fa578bf31bea37b8925d2e7df269435b8d9da14928b6253fc7226aef1c158a2929973908d6da608b10aaaa2e68428fc3de0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
